### ISSUE TITLE
No book variance

### ISSUE THREAD

**Issue by GodsTitan** [avivbeeri/kintsugi#4]
Only finding smite books, so far i have found 7 smite books and nothing else? is this a bug or is it intended am i doing somthing wrong?

**Comment by avivbeeri** [comment]
Where did you found them? It might be a balance issue on the loot tables

**Comment by GodsTitan** [comment]
I believe mostly in dungeon chests. I have been playing on better minecraft forge [BMC4] If that helps

**Comment by GodsTitan** [comment]
it could be an issue with:
L ootintegrations mod
Wersion: 1.201—3.4

Integrates items from loottables into other
loottables for intermod loot compatibility

**Comment by avivbeeri** [comment]
What I'd expect is that if you found a book in a dungeon chest (80% of chests), 50% of the time you'd get a Smite book, so 7 or 8 is unexpected. (See here for the data generation if you don't mind spoilers: https://github.com/avivbeeri/kintsugi/blob/1fabcd9c10b407b230b8d0174716d3d635be008f/src/main/java/net/infinitelimit/kintsugi/datagen/ModLootTableProvider.java#L31)

But, if other mods are interfering with mod table generation, I'm not really equipped to debug that. Kintsugi isn't inherently designed to work with other mods, it's expecting a vanilla minecraft environment.

**Comment by GodsTitan** [comment]
thank you so much for your help! im looking into see how i can summon loot tables so i can test this more in creative!

**Comment by avivbeeri** [comment]
Did you have much luck with this? I have a feeling it's to do with the unusual way I've set up the loot tables.
I might have a try at rewriting them later this week.

**Comment by GodsTitan** [comment]
I did find one other book that wasn't smite but I found about 3 more smite books before I removed the mod because I couldn't really get anything else. I personally think that this method is great but sadly I never found any documentation that covered where I'd find the books. With mods that add custom structures makeing the vanilla structures alot harder to find it makes finding the books feel impossible for a casual player like me. Additionally as a player I personally think that having an option to re roll a book into a random enchant would be a fun way to make the same books not be useless once you get to many. But I understand that as a developer it's ultimately your choise what you deem best for your mod. Thanks 😊.

**Comment by avivbeeri** [comment]
That's fair. I've yet to write a Wiki to cover where different things are found. I'm not really sure how to help with the custom structures issue.

I'm looking at different ways spare books can be repurposed, as that is a flaw in the current design.
Thank you for your feedback, and for giving it a fair go. I hope that you consider it again in the future :)

**Comment by GodsTitan** [comment]
Thanks 😊 looking forward to updates!!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
